version: BUILD{build}
skip_tags: true
configuration:
- Debug
- Release
shallow_clone: true
build:
  project: QuasarRAT.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: Bin
  name: binaries